# Generated by Django 5.2b1 on 2025-03-13 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_product_brand_alter_category_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='products_tags',
            options={'verbose_name': 'تگ ها', 'verbose_name_plural': 'تگ ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(verbose_name='فعال / غیر فعال'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(verbose_name='حذف نشده / حذف شده'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url_title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='URL عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_category', to='product_module.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(db_index=True, verbose_name='توضیجات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(verbose_name='حذف نشده / حذف شده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(db_index=True, max_length=360, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='products_tags',
            name='caption',
            field=models.CharField(db_index=True, max_length=300, verbose_name='تگ'),
        ),
        migrations.AlterField(
            model_name='products_tags',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_tag', to='product_module.product'),
        ),
    ]
