# Generated by Django 5.2b1 on 2025-03-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_userprofile_alter_contactus_is_read_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
