# Generated by Django 5.1.5 on 2025-05-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقاله'},
        ),
        migrations.RenameField(
            model_name='articlecomment',
            old_name='creat_date',
            new_name='create_date',
        ),
    ]
